[package]
name = "rust_webserver"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"  # For timestamp handling
clap = { version = "4.5", features = ["derive", "cargo"] }  # For command line argument parsing
fs2 = "0.4"  # For file locking
ctrlc = "3.4"  # For handling Ctrl+C gracefully
nix = { version = "0.27", features = ["process", "signal"] }  # For Unix operations like fork 